# fly.toml app configuration file generated for csmahjong on 2026-08-30T13:09:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csmahjong'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]
[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'csmahjong.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
